kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-seo-tag
  - jekyll-feed

url: https://kofi.sexy
logo: /android-chrome-192x192.png
theme_color: "#8a6a5e"

author:  { "twitter":  "hkgumbs" }
twitter: { "username": "hkgumbs" }

social:
  name: Kofi Gumbs
  links:
    - https://twitter.com/hkgumbs
    - https://github.com/hkgumbs
    - https://instagram.com/hkgumbs
    - https://youtube.com/c/hkofigumbs

collections:
  www:   { "output": true, "permalink": "/:path" }
  icons: { "output": true, "permalink": "/:path" }
  posts: { "output": true, "permalink": "/:categories/:slug" }

defaults:
  -
    scope:  { "path": "" }
    values: { "layout": "default" }

external_posts:
  - title: "Designing for trainer productivity"
    date: 2020-02-21 10:00:00
    url: "https://trainervision.com/articles/how-we-design-for-trainer-productivity"
  - title: "Inventing Options"
    date: 2019-03-18 10:00:00
    url: "https://engineering.hubtran.com/2019/03/18/inventing-options.html"
  - title: "How JSON decoding works in Elm—Part 3"
    date: 2017-08-29 10:00:00
    url: "https://8thlight.com/blog/kofi-gumbs/2017/08/29/elm-json-decoding-custom.html"
  - title: "How JSON decoding works in Elm—Part 2"
    date: 2017-07-17 10:00:00
    url: "https://8thlight.com/blog/kofi-gumbs/2017/07/17/elm-json-decoding-data-structures.html"
  - title: "How JSON decoding works in Elm—Part 1"
    date: 2017-06-28 10:00:00
    url: "https://8thlight.com/blog/kofi-gumbs/2017/06/28/elm-json-decoding-types.html"
  - title: "The Core of Erlang"
    date: 2017-05-02 10:00:00
    url: "https://8thlight.com/blog/kofi-gumbs/2017/05/02/core-erlang.html"
  - title: "Docker as a (workstation) service"
    date: 2016-07-27 10:00:00
    url: "https://8thlight.com/blog/kofi-gumbs/2016/07/27/docker-as-a-workstation-service.html"
  - title: "Becoming a professional learner"
    date: 2016-06-08 10:00:00
    url: "https://8thlight.com/blog/kofi-gumbs/2016/06/08/becoming-a-professional-learner.html"
  - title: "Using functions to make better abstractions"
    date: 2016-02-16 10:00:00
    url: "https://8thlight.com/blog/kofi-gumbs/2016/02/16/using-functions-to-make-better-abstractions.html"
