kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-seo-tag

author: Kofi Gumbs
url: https://kofi.sexy
logo: /android-chrome-192x192.png
twitter:
  username: hkgumbs

collections:
  www:   { "output": true, "permalink": "/:path" }
  blogs: { "output": true, "permalink": "/blog/:path" }
  talks: { "output": true, "permalink": "/talk/:path" }

external_posts:
  - title: "Inventing Options"
    date: 2019-03-18t08:00:00.00-05:00
    url: "https://engineering.hubtran.com/2019/03/18/inventing-options.html"
  - title: "How JSON decoding works in Elm—Part 3"
    date: 2017-08-29t08:00:00.00-05:00
    url: "https://8thlight.com/blog/kofi-gumbs/2017/08/29/elm-json-decoding-custom.html"
  - title: "How JSON decoding works in Elm—Part 2"
    date: 2017-07-17t08:00:00.00-05:00
    url: "https://8thlight.com/blog/kofi-gumbs/2017/07/17/elm-json-decoding-data-structures.html"
  - title: "How JSON decoding works in Elm—Part 1"
    date: 2017-06-28t08:00:00.00-05:00
    url: "https://8thlight.com/blog/kofi-gumbs/2017/06/28/elm-json-decoding-types.html"
  - title: "The Core of Erlang"
    date: 2017-05-02t08:00:00.00-05:00
    url: "https://8thlight.com/blog/kofi-gumbs/2017/05/02/core-erlang.html"
  - title: "Docker as a (workstation) service"
    date: 2016-07-27t08:00:00.00-05:00
    url: "https://8thlight.com/blog/kofi-gumbs/2016/07/27/docker-as-a-workstation-service.html"
  - title: "Becoming a professional learner"
    date: 2016-06-08t08:00:00.00-05:00
    url: "https://8thlight.com/blog/kofi-gumbs/2016/06/08/becoming-a-professional-learner.html"
  - title: "Using Functions to Make Better Abstractions"
    date: 2016-02-16t08:00:00.00-05:00
    url: "https://8thlight.com/blog/kofi-gumbs/2016/02/16/using-functions-to-make-better-abstractions.html"

empty_array: [] # https://github.com/jekyll/jekyll/issues/3246#issuecomment-68398379
