[build]
  command = "jekyll build"
  functions = "_functions"

[[redirects]]
  from = "/wedding"
  to = "https://wedding.kofi.sexy"

[[redirects]]
  from = "/grayarea"
  to = "https://grayarea.kofi.sexy"

[[redirects]]
  from = "/note"
  to = "/.netlify/functions/note?q=Hello%2C%20World!"

[[redirects]]
  from = "https://hkgumbs.netlify.com/*"
  to = "https://kofi.sexy/:splat"
  status = 301
  force = true
