[build]
  command = "jekyll build"

[[redirects]]
  from = "/wedding"
  to = "https://wedding.kofi.sexy"

[[redirects]]
  from = "/grayarea"
  to = "https://grayarea.kofi.sexy"

[[redirects]]
  from = "/public/*"
  to = "/blog/:splat"
