[build]
  command = "jekyll build"
  functions = "_functions"

[[redirects]]
  from = "/wedding"
  to = "https://wedding.kofi.sexy"

[[redirects]]
  from = "/grayarea"
  to = "https://grayarea.kofi.sexy"

[[redirects]]
  from = "/public/*"
  to = "/blog/:splat"

[[redirects]]
  from = "https://hkgumbs.netlify.com/*"
  to = "https://kofi.sexy/:splat"
  status = 301
  force = true
